kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    # Waves 0-99:    Cluster Config
    # Waves 100-199: Tenant namespaces
    # Waves 200-299: Operator Installation
    # Waves 300-399: Operator Instances and Cluster Services
    argocd.argoproj.io/sync-wave: "301"
  labels:
    gitops.ownedBy: openshift-gitops
  name: console-route-hsts
spec:
  destination:
    namespace: openshift-console
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: 01-cluster-admin/02-cluster-config/console-route-hsts
    repoURL: https://github.com/pittar-demos/secure-supply-chain.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy